import mongoose from "mongoose";
const collegeScheme = new mongoose.Schema({
  name,
  email,
  phone,
  address,
  city,
  state,
  country,
  pincode,
  website,
  collegeType,
  collegeCategory,
  collegeEstablishment,
  collegeCourses,
  collegeFees,
  collegeDescription,
  collegeImage,
  collegeVideo,
  collegeBrochure,
  collegeLogo,
  collegeGallery,
});
